# Generated by Django 4.2.13 on 2026-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('block_hash', models.CharField(max_length=64, unique=True)),
                ('previous_hash', models.CharField(max_length=64)),
                ('nonce', models.PositiveIntegerField(default=0)),
                ('timestamp', models.FloatField()),
                ('event_type', models.CharField(choices=[('REGISTERED', 'Product Registered'), ('TRANSFERRED', 'Transferred in Supply Chain'), ('SOLD', 'Sold to Customer'), ('FLAGGED', 'Flagged Suspicious')], max_length=20)),
                ('product_unit_serial', models.CharField(max_length=120)),
                ('actor_username', models.CharField(max_length=150)),
                ('actor_role', models.CharField(max_length=50)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
