# Generated by Django 4.2.13 on 2026-05-25 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unit_serial', models.CharField(db_index=True, max_length=120)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('SUSPICIOUS', 'Suspicious')], default='INVALID', max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('scanned_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
