# Generated by Django 4.2.13 on 2026-05-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_company_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('DISTRIBUTOR', 'Distributor'), ('CUSTOMER', 'Customer')], default='customer', max_length=20),
        ),
    ]
